version: 0.2

#env:
#  variables:

phases:
  install:
    commands:
      - cat /etc/issue
      - uname -a
      - whoami
      - pwd
      - apt update
      - apt -y install git
      - docker run hello-world
  pre_build:
    commands:
      - echo Clone kwaai-pai repo from Github...
      - git clone https://github.com/ShadNygren/kwaai-pai.git
      - echo Logging in to Amazon ECR...
      - #$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION
      - echo Build started on `date`
      - echo Building the Docker image...
      - BRANCH_NAME_LOWERCASE=$(echo $BRANCH_NAME | tr '[:upper:]' '[:lower:]')
      - PROJECT_NAME_LOWERCASE=$(echo $PROJECT_NAME | tr '[:upper:]' '[:lower:]')
      - IMAGE_REPO_NAME_LOWERCASE=$(echo $PROJECT_NAME-$BRANCH_NAME)
      - IMAGE_TAG_LOWERCASE=$(echo $IMAGE_TAG | tr '[:upper:]' '[:lower:]')
      - docker build -f Dockerfile -t $IMAGE_REPO_NAME_LOWERCASE:$IMAGE_TAG_LOWERCASE --build-arg AWS_ACCESS_KEY=$AWS_ACCESS_KEY --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_DEFAULT_REGION=AWS_DEFAULT_REGION .
      - docker tag $IMAGE_REPO_NAME_LOWERCASE:$IMAGE_TAG_LOWERCASE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_LOWERCASE:$IMAGE_TAG_LOWERCASE
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_LOWERCASE:$IMAGE_TAG_LOWERCASE
